<?php if (!empty($comms)) { ?>
    <div class="sort-comm-cont">
        <ul class="sort-comm" name="sort">
            <li class="sort-comm-item new-comm"> Newest </li>
            <li class="sort-comm-item love-comm"> Love </li>
        </ul>
    </div>
<?php }

$query_like   = "SELECT count(*) AS like_amt
                 FROM mpd_comm_like
                 WHERE comm_id = ?;";
$query_liked  = "SELECT count(*) AS like_amt
                 FROM mpd_comm_like
                 WHERE comm_id = ?
                 AND user_id = ?;";

$post_page = $dimport["post/post_page.phtml"]["redirect"];
foreach ($comms as $comm) {
    $user      = $records_get("mpd_user", "user_id", $comm["user_id"])[0];
    $like_amt  = $sql_query($query_like, [$comm["comm_id"]])[0]["like_amt"];
    $liked     = $sql_query($query_liked, [$comm["comm_id"], $_SESSION["u_id"]])[0]["like_amt"]; ?>
    <div class='media comm' id='<?= $comm["comm_id"] ?>'>
        <div class='media-bar media-bar-top'>
            <a href='index.php?page=profile/profile_page.phtml&user-id=<?= $user["user_id"] ?>'>
                <img src='/img/icons/profile-icon.png' class='media-bar-item post-profile'>
                <strong class='post-username'> <?= $user["username"] ?> </strong>
            </a>
            <img tabindex='0' src='/img/icons/more-icon.png' class='media-bar-item media-more'>
            <ul class='more-tog-menu'>
                <?php if ($_SESSION["u_id"] == $comm["user_id"]) { ?>
                    <li class='more-tog-menu-item comm-del-btn'> Delete </li>
                    <li class='more-tog-menu-item comm-edit-btn'
                        href='<?= $post_page."&post-id=".$comm["post_id"]."&comm-id=".$comm["comm_id"] ?>'> Edit </li>
                <?php } else { ?>
                    <li class='more-tog-menu-item comm-report-btn'> Report </li>
                <?php } ?>
            </ul>
        </div>
        <div class='media-cont comm-cont'>
            <p class='text'> <?= $comm["comm"] ?> </p>
            <p class='text date media-date'> <?= $comm["comm_dt"] ?> </p>
        </div>
        <div class="see-more"> <p class="see-more-text"> See More </p> </div>
        <div class='media-bar media-bar-bottom'>
            <img src='/img/icons/heart-icon.png' class='media-bar-item love-btn comm-love-btn'>
            <em class='like-amt' title='<?= $liked ?>'> <?= $like_amt ?> </em>
            <?php if (empty($post)) { ?>
                <a href="<?= $post_page."&post-id=".$comm["post_id"] ?>">
                    <img src='/img/icons/source-icon.png' class='media-bar-item comm-source-btn'>
                </a>
            <?php } ?>
        </div>
    </div>
<?php }

$alter_form = "comm";
require $dimport["common/alter_forms.phtml"]["path"];
