<?php
$comm_text = "";
if (!empty($_GET["comm-id"])) {
	require_once $dimport["db/db_funcs.php"]["path"];

	$comm = $records_get("mpd_comm", "comm_id", $_GET["comm-id"]);
	if (empty($comm))
		redirect($dimport["home/home_page.phtml"]["redirect"]."&error=invalid-comm");
	$comm = $comm[0];

	if ($comm["user_id"] != $_SESSION["u_id"])
		redirect($dimport["home/home_page.phtml"]["redirect"]."&error=invalid-comm");

	$comm_text = str_replace("~_", "\n", $comm["comm"]);
}

if (empty($comm_text)) {
	$action     = $dimport['comm/make_comm.php']['redirect'];
	$comm_text  = "";
} else $action = $dimport['comm/edit_comm.php']['redirect']."&comm-id=".$comm['comm_id']; ?>

<form class="theme-box make-comment-cont" action="<?= $action ?>" method="POST">
    <textarea class="main-input main-textarea comment-textarea block-middle" name="comm" placeholder="add a comment..." pattern=".{0,8000}" required><?= $comm_text ?></textarea>
	<input type="hidden" name="post-id" value="<?= $post["post_id"] ?>">
	<?= $csrf_form_get ?>
	<button class="main-button media-button block-right" type="submit" name="submit"> Comment </button>
</form>
