<div class="theme-box page-item">
    <div class="dropdown dropdown-filter" tabindex="0">
        <div class="dropdown-btn"> Sort &nbsp▾ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item filter{sort:new}"> New </li>
            <li class="dropdown-item filter{sort:like}"> Likes </li>
            <li class="dropdown-item filter{sort:comment}"> Comments </li>
        </ul>
    </div>
    <div class="dropdown dropdown-filter" tabindex="0">
        <div class="dropdown-btn"> Date &nbsp▾ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item filter{date:today}"> Today </li>
            <li class="dropdown-item filter{date:week}"> Week </li>
            <li class="dropdown-item filter{date:month}"> Month </li>
            <li class="dropdown-item filter{date:year}"> Year </li>
            <li class="dropdown-item filter{date:all}"> All </li>
        </ul>
    </div>
    <form class='form-search float-right' method='GET'>
        <input class='main-input sort-bar-input' name='search' placeholder='search...' required>
    </form>
</div>
