<div class="theme-box page-item">
    <div class="dropdown" tabindex="0">
        <div class="dropdown-btn"> Sort &nbsp▾ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item new-post"> New </li>
            <li class="dropdown-item love-post"> Likes </li>
            <li class="dropdown-item comments"> Comments </li>
        </ul>
    </div>
    <div class="dropdown" tabindex="0">
        <div class="dropdown-btn"> Date &nbsp▾ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item today-post"> Today </li>
            <li class="dropdown-item week-post"> Week </li>
            <li class="dropdown-item month-post"> Month </li>
            <li class="dropdown-item year-post"> Year </li>
            <li class="dropdown-item all-post"> All </li>
        </ul>
    </div>
    <form class='float-right' method='GET'>
        <input class='main-input sort-bar-input' name='search' placeholder='search...' required>
    </form>
</div>
