<?php
$query_like     = "SELECT count(*) AS like_amt
                   FROM post_like
                   WHERE post_id = ?;";
$query_comment  = "SELECT count(*) AS comment_amt
                   FROM comment
                   WHERE post_id = ?;";
$query_liked    = "SELECT count(*) AS like_amt
                   FROM post_like
                   WHERE post_id = ?
                   AND user_id = ?;";

$post_page       = $dimport["post/post_page.phtml"]["redirect"];
$make_post_page  = $dimport["post/make_post_page.phtml"]["redirect"];
foreach ($posts as $post) {
    $user         = $records_get("pd_user", "user_id", $post["user_id"])[0];
    $like_amt     = $sql_query($query_like, [$post["post_id"]])[0]["like_amt"];
    $comment_amt  = $sql_query($query_comment, [$post["post_id"]])[0]["comment_amt"];
    $liked        = $sql_query($query_liked, [$post["post_id"], $_SESSION["u_id"]])[0]["like_amt"]; ?>
    <div class="main-cont-item theme-box page-item media post" id='<?= $post["post_id"] ?>'>
        <div class="media-bar">
            <a class="media-bar-item" href='index.php?page=profile/profile_page.phtml&user-id=<?= $user["user_id"] ?>'> <?= $user["username"] ?> </a>
            <div class="media-bar-item media-bar-info main-date date"> <?= $post["post_dt"] ?> </div>
            <div class="float-right">
                <div class="dropdown" tabindex="0">
                    <div class="dropdown-btn">• • •</div>
                    <ul class="dropdown-cont position-right">
                        <?php if ($_SESSION["u_id"] == $post["user_id"]) { ?>
                            <li class="dropdown-item post-del-btn"> Delete </li>
                            <li class="dropdown-item post-edit-btn" href='<?= $make_post_page."&post-id=".$post["post_id"] ?>'> Edit </li>
                        <?php } else { ?>
                            <li class="dropdown-item"> Report </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="main-title post-title"> <?= $post["title"] ?> </div>
        <div class="media-cont">
            <div class="media-text see-more-text"> <?= $post["text"] ?> </div>
        </div>
        <div class="see-more"> See More </div>
        <div class="media-bar">
            <div class="media-bar-item like-btn">
                <img class="invert-icon media-bar-icon like-icon check{state:<?= $liked ?>}" src="/img/icons/like-icon.png">
                <div class="media-bar-icon-value like-amt"> <?= $like_amt ?> </div>
            </div>
            <a class="media-bar-item" href="<?= $post_page."&post-id=".$post["post_id"] ?>">
                <img class="invert-icon media-bar-icon" src="/img/icons/comment-icon.png">
                <div class="media-bar-icon-value"> <?= $comment_amt ?> </div>
            </a>
        </div>
    </div>
<?php }

$alter_form = "post";
require $dimport["media/alter_forms.phtml"]["path"];
