<?php
$alter = [
    "post" => [
        "delete"  => $dimport['post/delete_post.php']['redirect'],
        "love"    => $dimport['post/love_post.php']['redirect']
    ],
    "comm" => [
        "delete"  => $dimport['comm/delete_comm.php']['redirect'],
        "love"    => $dimport['comm/love_comm.php']['redirect']
    ]
]; ?>

<form class="<?= "$alter_form-delete-form" ?>"
      style="display: none;"
      action="<?= $alter[$alter_form]["delete"] ?>"
      method="POST">
    <input name="media-id" type="text">
    <?= $csrf_form_get ?>
    <button name="submit" type="submit"></button>
</form>

<form class="<?= "$alter_form-love-form" ?>"
      style="display: none;"
      action="<?= $alter[$alter_form]["love"] ?>"
      method="POST">
    <input name="media-id" type="text">
    <?= $csrf_form_get ?>
    <button name="submit" type="submit"></button>
</form>
