<?php
$query_next = "SELECT * FROM $table
               $filter_query
               ORDER BY $order_by DESC
               LIMIT ".($pagin_start+$pagin_amt).",1;";

if (empty($search_val)) $search_val = "";
$next = $sql_query($query_next, [$search_val, $search_val]); ?>

<div class="pagin-cont">
    <?php if ($pagin_page != 0) { ?>
        <img class="pagin-arrow pagin-prev" src="/img/icons/arrow-icon.png">
    <?php } if (count($next) > 0) { ?>
        <img class="pagin-arrow pagin-next" src="/img/icons/arrow-icon.png">
    <?php } ?>
</div>
