<?php
$post_like_amt = "SELECT count(*) AS like_amt
                  FROM mpd_post_like JOIN mpd_post
                  ON mpd_post_like.post_id = mpd_post.post_id
                  AND mpd_post.user_id = ?;";
$comm_like_amt = "SELECT count(*) AS like_amt
                  FROM mpd_comm_like JOIN mpd_comm
                  ON mpd_comm_like.comm_id = mpd_comm.comm_id
                  AND mpd_comm.user_id = ?;";

$post_like_amt = $sql_query($post_like_amt, [$user["user_id"]])[0]["like_amt"];
$comm_like_amt = $sql_query($comm_like_amt, [$user["user_id"]])[0]["like_amt"];

$like_amt = $post_like_amt + $comm_like_amt;

$comm_page   = $dimport["comm/comm_page.phtml"]["redirect"];
$setts_page  = $dimport["setts/setts_page.phtml"]["redirect"]; ?>
<div class="theme-box page-item media post">
    <div class="main-title profile-menu-title"> <?= $user['username'] ?> </div>
    <div class="profile-section">
        <div class="profile-menu-desc">
            <img class="profile-menu-desc-icon invert-icon" src="/img/icons/cake-icon.png" alt="">
            <b class="profile-menu-desc-key"> Registered </b>
            <div class="profile-menu-desc-value main-date float-right"> <?= $user['user_dt'] ?> </div>
        </div>
        <div class="profile-menu-desc">
            <img class="profile-menu-desc-icon invert-icon" src="/img/icons/heart-checked-icon.png" alt="">
            <b class="profile-menu-desc-key"> Likes </b>
            <div class="profile-menu-desc-value float-right"> <?= $like_amt; ?> </div>
        </div>
    </div>
    <div class="profile-menu-nav">
        <?php if ($user["user_id"] == $_SESSION["u_id"]) { ?>
            <a href="<?= $setts_page ?>">
                <button class='main-button card-button'> Settings </button>
            </a>
        <?php } ?>
        <a href="<?= $comm_page."&user-id=".$user['user_id'] ?>">
            <button class='main-button card-button'> Comments </button>
        </a>
    </div>
</div>
