<div class='dropdown'>
    <div tabindex='0' class='dropdown-btn header-loc'> sort </div>
    <ul class='dropdown-cont header-settings' name='sort'>
        <li class='love-post'> love </li>
        <li class='comments'> comment </li>
        <li class='new-post'> new </li>
    </ul>
</div>
<div class='dropdown'>
    <div tabindex='0' class='dropdown-btn header-loc'> date </div>
    <ul class='dropdown-cont header-settings' name='date'>
        <li class='today-post'> today </li>
        <li class='week-post'> last week </li>
        <li class='month-post'> last month </li>
        <li class='year-post'> last year </li>
        <li class='all-post'> all time </li>
    </ul>
</div>
<form class='dropdown form-search' method='GET'>
    <input class='header-search' name='search' placeholder='search...' required>
</form>
