<div class='dropdown'>
  <div tabindex='0' class='dropdown-btn' id='header-loc'> sort </div>
  <ul class='dropdown-cont' id='header-settings' name='sort'>
    <li id='love-post'> love </li>
    <li id='comments'> comment </li>
    <li id='new-post'> new </li>
  </ul>
</div>
<div class='dropdown'>
  <div tabindex='0' class='dropdown-btn' id='header-loc'> date </div>
  <ul class='dropdown-cont' id='header-settings' name='date'>
    <li id='today-post'> today </li>
    <li id='week-post'> last week </li>
    <li id='month-post'> last month </li>
    <li id='year-post'> last year </li>
    <li id='all-post'> all time </li>
  </ul>
</div>
<form class='dropdown' id='form-search' method='GET'>
  <input id='header-search' name='search' placeholder='search...' required>
</form>
